### ISSUE TITLE
Override test names with docstring?

### ISSUE THREAD

**Issue by cartertinney** [renanivo/pytest-testdox#19]
It would be really nice if test names could be overridden by a (short) docstring on the test.

Since underscores are always removed from test case names, it can sometimes reduce legibility, specifically when referring to particular function/method names, which have underscores.

e.g.
```python
def test_send_to_output_calls_transport_wrap_data_on_message()
```
Always results in 

```
 [x] send to output calls transport wrap data on message
```

When the ideal output would be

```
 [x] send_to_output calls transport_wrap_data on message
```

Ideally, you could override this behavior by specifying the docstring (optionally):

```python
def test_send_to_output_calls_transport_wrap_data_on_message()
    """TESTDOX: send_to_output calls transport_wrap_data on message"""
```

**Comment by renanivo** [comment]
I liked that idea. But I have a question: Why do you think a `TESTDOX` prefix would be desirable instead of using the first line of any docstring?

I feature like that should also have a configuration flag to turn it off.

**Comment by cartertinney** [comment]
My reasoning was that some users may want to have information in their docstrings about the test itself. You wouldn't want to grab all of that, you'd probably just want to parse out the designated one-line test name section, thus the `TESTDOX` prefix to identify it.

e.g.
```python
def test_send_to_output_calls_transport_wrap_data_on_message()
    """TESTDOX: send_to_output calls transport_wrap_data on message

    Here is a docstring with more information about the specifics of the test
    """
```

My thinking is that this would remove the need for a flag, and also give the user flexibility to allow for their docstring to contain additional info. But I don't mind also having a flag either, as long as I can still put non-name related data in the docstring

**Comment by renanivo** [comment]
Got it. We could put the docstring prefix in a configuration flag too. I'll put the "help wanted" label in this issue, because I'll not be able to work on it in the next couple weeks.

**Comment by RomuloOliveira** [comment]
Maybe  `pytest.mark` can be used do this, I do not know exactly how it is implemented internally, but it may be easier to do and cleaner than using docstring. Example: 

```python
@pytest.mark.testdox('send_to_output calls transport_wrap_data on message')
def test_send_output():
    ...
```

**Comment by renanivo** [comment]
@RomuloOliveira I prefer your suggestion as it is easier to develop, doesn't need feature flags and is impossible to annoy people who already uses docstrings in tests for different reasons.

**Comment by cartertinney** [comment]
I agree, using pytest.mark is a great idea.

**Comment by renanivo** [comment]
I removed the "help wanted" label and assigned it to myself, as I started implementing it.

**Comment by renanivo** [comment]
> Also, can we get this on test classes too?

I started thinking about it when I put my hands on the code. In the beginning I started implementing it with only the `@pytest.mark.testdox`, but what do you think about using the names that are common for functions in spec BDD: `@pytest.mark.describe` (for classes) and `pytest.mark.it` (for functions).

Ex:

```python
@pytest.mark.describe('Terminal Printer')
class TestPrinter:

    @pytest.mark.it('should print a message to stdout')
    def test_stdout(self):
        ...
```

I googled it and looks like it is not in use by other plugins.

**Comment by cartertinney** [comment]
I like that idea. Reminds me of Mocha for Nodejs.
