### ISSUE TITLE
Incompatibility between pytest.mark.it and pytest.mark.parametrize

### ISSUE THREAD

**Issue by cartertinney** [renanivo/pytest-testdox#22]
I've been playing around with the new `pytest.mark.it` and `pytest.mark.describe` features, and they're wonderful (thanks for implementing those), but I have hit an issue with regard to parametrization.

When parametrizing a test, with `pytest.mark.parametrize`, the test is repeated several times with different parameters, and formats the different parameter ids in square brackets, e.g.:

```cmd
 [x] from authentication provider boundary case transport name[ALL CAPS]
 [x] from authentication provider boundary case transport name[mIxEd CaSe]
```

However, when using the name overrides, it overrides, the square bracket parameter ids are lost, and the name given by `pytest.mark.it` is just simply repeated twice:

```cmd
 [x] from_authentication_provider boundary case transport_name
 [x] from_authentication_provider boundary case transport_name
```
Ideally, I can use name overrides while keeping parameter ids.

**Comment by RomuloOliveira** [comment]
@renanivo I can take a look at this issue if you want some help

**Comment by RomuloOliveira** [comment]
@cartertinney #23 should fix it

**Comment by cartertinney** [comment]
It did, thanks very much.
