### ISSUE TITLE
Format abbreviations properly

### ISSUE THREAD

**Issue by renanivo** [renanivo/pytest-testdox#3]
Currently the title formatter always put a space before an uppercase letter, so a test `def test_calls_an_API` ends up formatted `calls an A P I`. It should not put a space between uppercased letters.

**Comment by RomuloOliveira** [comment]
I checked and the title formatter actually works as you described:

```
>>> formatters.format_title('test_calls_an_API')
'calls an API'
```

The class name formatter, however, has that problem:

```
>>> formatters.format_class_name('TestMyAPI')
'My A P I'
```

This problem is a little bit tricky, because `TestMyAPI` should be formatted as `MyAPI` but with `TestAThing` the expected output is `A Thing`.

**Comment by renanivo** [comment]
What if the formatter looked at the letters before and after the uppercased letters?

Egg:
```
     It needs a space before. There's a lowercase letter after `T`
     v
TestAThing
    ^
    There's a lowercase letter before the uppercase `A`, it needs a space before.
```

Another example:
```
      It needs a space before, there's an lowercase letter before `A`.
      v
TestMyAPI
    ^  ^
    ^  Ain't no need for space before `P`. No lowercase letter besides.
    ^
    It needs space before. There's a lowercase letter before AND after `M`!
```
