### ISSUE TITLE
Convert README from ReStructured Text to MarkDown

### ISSUE THREAD

**Issue by renanivo** [renanivo/pytest-testdox#38]
Besides being my personal favorite, MarkDown is more popular so it is easier to be edited by more people.

Do not forget to update [long_description_content_type](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) in `setup.py` after converting the file.

**Comment by hugovk** [comment]
Please see PR https://github.com/renanivo/pytest-testdox/pull/39.
